edition = "2021"
newline_style = "Unix"
hard_tabs = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
force_multiline_blocks = true
use_field_init_shorthand = true
condense_wildcard_suffixes = true
binop_separator = "back"
match_block_trailing_comma = true
